services:
  mysql:
    image: mysql:8.0
    container_name: callback-mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: callback_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3305:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data: